[general]
import = [
  "~/.config/alacritty/themes/gruvbox-material-medium-dark.toml",
]

[font]
size = 11

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Semibold Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Semibold"

[window]
decorations_theme_variant = "Dark"
dynamic_padding = true
decorations = "None"

[window.padding]
x = 8
y = 8
