#!/usr/bin/env zsh

panel_fifo="/tmp/panel_fifo_${USER}"
panel_pid_file='/tmp/bar-pid'
panel_name='bar_panel'

width=$(xrandr 2> /dev/null | grep current | awk '{print $8}')
height=55
geometry="${width}x${height}+0+0"
border=4
font_offset=-42

font1='Droid Sans:size=10'
font2='Droid Sans:size=10:style=bold'

icon1='FontAwesome:size=12'
icon2='FontAwesome:size=56'

scheme='nameless'

fg_color=$(~/.colors/get-color ${scheme} black)
bg_color=$(~/.colors/get-color ${scheme} b_white)
red=$(~/.colors/get-color ${scheme} red)
yellow=$(~/.colors/get-color ${scheme} yellow)
green=$(~/.colors/get-color ${scheme} green)
cyan=$(~/.colors/get-color ${scheme} cyan)
blue=$(~/.colors/get-color ${scheme} blue)
magenta=$(~/.colors/get-color ${scheme} purple)

pad='    '
space='  '

