#!/usr/bin/env zsh

source "$(dirname $0)/config"

format_volume() {
  local info=${1}
  local icon_color=''

  [ "$(echo $info | awk -F '[][]' '{print $6}')" = 'off' ] && icon_color="%{F${red}}"

  local vol=$(echo $info | awk -F '[][]' '{print $2}' | head -1 | sed 's/%//')

  local icon=$(if (( vol <= 100 && vol >= 41 )); then
    echo ''
    return
  elif (( vol <= 40 && vol >= 1 )); then
    echo ' '
    return
  else
    echo '  '
    return
  fi)

  echo "${vol}${space}${icon_color}${icon}%{F-}"
}

format_workspace() {
  echo "${1}${space}"
}

format_active_window() {
  [ -n "${1}" ] && echo "%{+u U${blue} T2}//%{T-}${space}${1}${space}%{-u U-}"
}

format_user() {
  echo "%{+u U${blue} T2}${space}${1}${space}%{-u U- T-}"
}

format_updates() {
  local icon_color=''
  [ "$1" -eq 0 ] && return

  [ "$1" -ge 20 ] && icon_color="%{F${red}}"

  echo "${1}${space}${icon_color}%{F-}"
}

format_center() {
  echo
}

format_left() {
  echo "${user}${active_window}"
}

format_right() {
  echo "${updates}${pad}${workspace}${pad}${volume}${pad}${clock}${pad}"
}

while read -r line; do
  case $line in
    A*) active_window=$(format_active_window "${line:1}") ;;
    C*) clock=${line:1} ;;
    V*) volume=$(format_volume "${line:1}") ;;
    U*) user=$(format_user "${line:1}") ;;
    W*) workspace=$(format_workspace "${line:1}") ;;
    P*) updates=$(format_updates "${line:1}") ;;
  esac

  echo "%{O50}$(format_left)%{c}$(format_center)%{r}$(format_right)%{O50}"
done

