#!/usr/bin/env zsh

source "$(dirname $0)/config"

underline() {
  echo "%{+u U${1}}${2}%{-u U-}"
}

format_volume() {
  local info=${1}
  local ucolor=$bg_color

  [ "$(echo $info | awk -F '[][]' '{print $6}')" = 'off' ] && ucolor=$red

  local vol=$(echo $info | awk -F '[][]' '{print $2}' | head -1 | sed 's/%//')

  local icon=$(if (( vol <= 100 && vol >= 41 )); then
    echo ''
    return
  elif (( vol <= 40 && vol >= 1 )); then
    echo ' '
    return
  else
    echo '  '
    return
  fi)

  echo $(underline "$ucolor" "${vol}${space}${icon}")
}

format_workspace() {
  echo $(underline "$bg_color" "${1}${space}")
}

format_active_window() {
  [ -n "${1}" ] && echo "%{T2}//%{T-}${space}${1}"
}

format_user() {
  echo "%{T2}${1}%{T-}"
}

format_updates() {
  local ucolor=$bg_color
  [ "$1" -eq 0 ] && return

  [ "$1" -ge 20 ] && ucolor=$red

  echo $(underline "$ucolor" "${1}${space}${icon_color}")
}

format_center() {
  echo
}

format_left() {
  echo $(underline "$blue" "${user}${space}${active_window}")
}

format_right() {
  echo "$updates$pad$workspace$pad$volume$pad$clock"
}

while read -r line; do
  case $line in
    A*) active_window=$(format_active_window "${line:1}") ;;
    C*) clock=${line:1} ;;
    V*) volume=$(format_volume "${line:1}") ;;
    U*) user=$(format_user "${line:1}") ;;
    W*) workspace=$(format_workspace "${line:1}") ;;
    P*) updates=$(format_updates "${line:1}") ;;
  esac

  echo "%{O50}$(format_left)%{c}$(format_center)%{r}$(format_right)%{O50}"
done

