#!/bin/sh

scheme='nameless'

bspc config top_padding       70
bspc config right_padding     20
bspc config bottom_padding    20
bspc config left_padding      20
bspc config window_gap        30
bspc config border_width      0

# TODO move to scheme config
bspc config normal_border_color   "$(~/.colors/get-color $scheme white)"
bspc config active_border_color   "$(~/.colors/get-color $scheme white)"
bspc config focused_border_color  "$(~/.colors/get-color $scheme white)"
bspc config presel_feedback_color "$(~/.colors/get-color $scheme blue)"

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true
bspc config focus_follows_pointer true
bspc config external_rules_command ~/.config/bspwm/external-rules

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_motion_interval 10

bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9

~/.config/bspwm/panel/bar &

