#!/bin/sh

scheme='nameless'

bspc config top_padding       75
bspc config right_padding     25
bspc config bottom_padding    25
bspc config left_padding      25
bspc config window_gap        30
bspc config border_width      2

# TODO move to scheme config
bspc config normal_border_color   "$(~/.colors/get-color $scheme black)"
bspc config active_border_color   "$(~/.colors/get-color $scheme black)"
bspc config focused_border_color  "$(~/.colors/get-color $scheme white)"

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true
bspc config focus_follows_pointer true

bspc monitor DP-0 -d 1 2 3 4 5 6

~/.config/bspwm/panel/bar &

