#! /bin/sh

bspc config top_padding         46
bspc config border_width         2
bspc config window_gap          12

bspc config normal_border_color '#2D2D2D'
bspc config active_border_color '#2D2D2D'
bspc config focused_border_color '#F2F0EC'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true

bspc monitor DP-0 -d 1 2 3 4 5 6

~/.config/bspwm/panel/bar &

