#!/usr/bin/env zsh

wid=$1
class=$2
instance=$3
title=$(xtitle "$wid")

# Debug
# echo "$wid $class $instance $(xtitle "$wid")" >> /tmp/bspc-external-rules

[[ $title = 'Slack Call Minipanel' ]] && echo -e 'state=floating\nsticky=on'

hangouts_screen_share='Google[[:space:]]Hangouts[[:space:]]is[[:space:]]sharing[[:space:]]*'

if [[ -z ${class// } && -z ${instance// } ]]; then
  [[ $title =~ $hangouts_screen_share ]] && echo state=floating
fi

