#!/usr/bin/env zsh

wid=$1
class=$2
instance=$3

hangouts_screen_share='Google[[:space:]]Hangouts[[:space:]]is[[:space:]]sharing[[:space:]]*'

if [[ -z ${class// } && -z ${instance// } ]]; then
  title=$(xtitle "$wid")

  [[ $title =~ $hangouts_screen_share ]] && echo state=floating
fi

