#!/usr/bin/env zsh

width=$(xrandr 2> /dev/null | grep current | awk '{print $8}')
geometry="${width}x30x0x0"

font1='Droid Sans:pixelsize=12:style=bold'
font2='Droid Sans:pixelsize=12'

icon1='FontAwesome:pixelsize=16'

scheme='base16-eighties'

fg_color=$(~/.colors/get-color ${scheme} fg)
bg_color=$(~/.colors/get-color ${scheme} bg)
red=$(~/.colors/get-color ${scheme} red)
orange=$(~/.colors/get-color ${scheme} orange)
yellow=$(~/.colors/get-color ${scheme} yellow)
green=$(~/.colors/get-color ${scheme} green)
cyan=$(~/.colors/get-color ${scheme} cyan)
blue=$(~/.colors/get-color ${scheme} blue)
purple=$(~/.colors/get-color ${scheme} purple)
brown=$(~/.colors/get-color ${scheme} brown)

pad='    '
space='  '

